"""Genero adicionado na tabela livro

Revision ID: 85f195498392
Revises: 3a69cbd00302
Create Date: 2026-08-27 16:07:22.798698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f195498392'
down_revision = '3a69cbd00302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genero', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livro', schema=None) as batch_op:
        batch_op.drop_column('genero')

    # ### end Alembic commands ###
